define you = Character("You")
define mystery = Character("??#@!")
define empty = Character(None)
define mom = Character("Mom")
define doctor = Character("Doctor")
define death = Character("******")
define speaker = Character("Narrator")
